version: '3.7'

services:
  web:
    build:
      context: .
    environment:
      - NEXT_PUBLIC_GA_ID=${NEXT_PUBLIC_GA_ID}
    entrypoint: entrypoint.sh
    ports:
      - "8001:3000"
    tty: true
    stdin_open: true
